### ISSUE TITLE
Could not retrieve object of type 'IJsonSerializer' from ASP.NET Core's dependency container. 

### ISSUE THREAD

**Issue by darting** [giraffe-fsharp/Giraffe.AzureFunctions#3]
Hi there, I am trying to use Giraffe on Azure function. but I got this error `Could not retrieve object of type 'IJsonSerializer' from ASP.NET Core's dependency container. Please register all Giraffe dependencies by adding `services.AddGiraffe()` to your startup code`. Any idea?

the source code is there: 
https://github.com/darting/TryAzureFunctions

`/api/healths/ping` is working
`/api/healths/hello` not working since its a json response

Thanks

**Comment by JonCanning** [comment]
Startup has to be in a separate assembly, this had me scratching my head for a long time 😟

**Comment by darting** [comment]
awesome .. its working now !! you should write it to README hahah, thanks

**Comment by yetanotherlogonfail** [comment]
sorry separate assembly?? exactly what is the fix?

**Comment by yetanotherlogonfail** [comment]
Ah got it, I need to add below, to my routing file ?

let configureServices (services : IServiceCollection) =
    // Add Giraffe dependencies
    services.AddGiraffe() |> ignore
