### ISSUE TITLE
Host error after each function execution

### ISSUE THREAD

**Issue by Dzoukr** [giraffe-fsharp/Giraffe.AzureFunctions#4]
Hello guys,
I just stumble upon strange error running Giraffe on Azure Functions v3 (`netcoreapp3.1`). Now after each request I got this error:

```
[11.12.2019 21:32:44] Executing 'Index' (Reason='This function was programmatically called via the host APIs.', Id=ab3a2800-3f86-4d63-914b-1e1e61f4432b)
[11.12.2019 21:32:44] ----SOME EXECUTION LOGS----
[11.12.2019 21:32:44] Executed 'Index' (Succeeded, Id=ab3a2800-3f86-4d63-914b-1e1e61f4432b)
[11.12.2019 21:32:44] An unhandled host error has occurred.
[11.12.2019 21:32:44] Microsoft.AspNetCore.Server.Kestrel.Core: StatusCode cannot be set because the response has already started.
```
Function is exactly the same as in demo project - https://github.com/giraffe-fsharp/Giraffe.AzureFunctions/blob/master/demo/Run.fs#L31-L39

I worked great on `netcoreapp2.1` - any idea what could cause this?

**Comment by JonCanning** [comment]
I've updated the sample to use 3.1

**Comment by toburger** [comment]
Seems related: https://github.com/giraffe-fsharp/Giraffe.AzureFunctions/issues/1#issuecomment-603737967

**Comment by toburger** [comment]
The following code fixes the error:

```fsharp  
task {
    let! _ = app func req.HttpContext
    do! req.HttpContext.Response.Body.FlushAsync()
    return Microsoft.AspNetCore.Mvc.EmptyResult()
}
```

Source: https://stackoverflow.com/questions/45675102/asp-net-core-middleware-cannot-set-status-code-on-exception-because-response-ha

**Comment by toburger** [comment]
Still I'm not happy with this workaround.
I don't want to see **any** reference to an MVC dependency inside a plain Giraffe project.
So I wonder what causes this error at all and then eliminate the root cause.

**Comment by Dzoukr** [comment]
Hi @toburger,
you are right - any referrence to MVC inside Giraffe project sounds scary 😄 but thanks! I'll try it and I think we can close this issue (until MS breaks something again).

**Comment by toburger** [comment]
```fsharp
[<FunctionName "Giraffe">]
let run ([<HttpTrigger (AuthorizationLevel.Anonymous, Route = "{*any}")>] req : HttpRequest, context : ExecutionContext, log : ILogger) =
  let hostingEnvironment = req.HttpContext.GetHostingEnvironment()
  hostingEnvironment.ContentRootPath <- context.FunctionAppDirectory
  let func = Some >> Task.FromResult
  { new Microsoft.AspNetCore.Mvc.IActionResult with
      member _.ExecuteResultAsync(ctx) = 
        app func ctx.HttpContext :> Task 
```

This implementation also works. Still there is this pesky `Mvc` namespace... 🙈

**Comment by Dzoukr** [comment]
Btw, this one works as well...

```fsharp
task {
    let! _ = app func req.HttpContext
    return Microsoft.AspNetCore.Mvc.EmptyResult()
}
```
