### ISSUE TITLE
Use `func start` directly instead of workflow in `startLocal.sh`

### ISSUE THREAD

**Issue by toburger** [giraffe-fsharp/Giraffe.AzureFunctions#7]
It is now much easier to start a local development instance than it was before.
The code gets built automatically when starting the project via `func start` after this PR was merged some time ago: https://github.com/Azure/azure-functions-core-tools/pull/1405

The developer experience is now on par with the C# experience and there is no need anymore for a complicated workflow.

I've added the simplified startup code to my pull request: https://github.com/giraffe-fsharp/Giraffe.AzureFunctions/pull/6

**Comment by dustinmoris** [comment]
Awesome, thank you very much! I've merged the PR which I blieve means this issue is done?

**Comment by toburger** [comment]
Yes, thanks for the merge!
